### ISSUE TITLE
Failing link in Spanish book

### ISSUE THREAD

**Issue by oscaretu** [nushell/book#116]
The last link of page

https://www.nushell.sh/book/es/indice.html

is

**Mapa Nushell de operadores** - Guía para ayudar a entender los operadores.

It point to the wrong address

https://www.nushell.sh/book/es/mapa_nushell_operador_map.md

instead of the right one

<https://www.nushell.sh/book/es/mapa_nushell_operador_map.html>

**Comment by jonathandturner** [comment]
@andrasio ^

**Comment by andrasio** [comment]
@oscaretu  ¡Gracias Oscar! ¿Te animas al fix? Sin presión. Puedo hacerlo yo.

**Comment by andrasio** [comment]
@jonathandturner ccc
