### ISSUE TITLE
installation instructions could be more stable-gentle

### ISSUE THREAD

**Issue by robg204** [nushell/book#18]
Would consider using cargo +nightly install nu, or rustup override add nightly after git clone as a more kind way to use nightly without requiring changing the global default.  Feels a little more gentle.

**Comment by jonathandturner** [comment]
@robg204 - sorry for the delay. If you're interested, you could file a PR. Otherwise, we'll do this as part of a round of book updates (which hopefully won't be too long from now)

**Comment by jonathandturner** [comment]
Now that we're on stable by default, this should be fixed
