### ISSUE TITLE
Can I translate it into Chinese?

### ISSUE THREAD

**Issue by deliangyang** [nushell/book#22]
Add a new directory named zh-cn.

**Comment by androbtech** [comment]
@deliangyang Yes! Please do.

**Comment by jonathandturner** [comment]
@deliangyang if you're still interested in translating to zh-cn, we'd love to add it :)

**Comment by jonathandturner** [comment]
Closing, but @deliangyang if you're interested please do translate the book. We'd be happy to add it.

**Comment by zombie110year** [comment]
I'm glad to translate this book into chinese, I will progressively do it.

See my [repo](https://github.com/zombie110year/nushell-book) for progression.
