### ISSUE TITLE
types_of_data.md mentions "where { $it.size > 10kb }" which is unfamiliar and doesn't seem to work

### ISSUE THREAD

**Issue by toolness** [nushell/book#37]
Hello! I am using nuShell version 0.4.0 on Windows.

I was going through the book (which is great!) and noticed a passage in the [Types of data](https://book.nushell.sh/en/types_of_data) section that mentions the following:

> Blocks represent a block of code in Nu. For example, in the command `where { $it.size > 10kb }` the block is the portion contained in curly braces, `{ $it.size > 10kb }`. Blocks are a useful way of representing code that can be executed on each row of data.

This was confusing to me because I'd seen `where size > 10kb` but not what was written.  I then tried typing what was written as part of a pipe starting with `ls` but it said:

```
C:\Users\Atul> ls **/*.txt | where { $it.size > 10kb }
error: Type Error
- shell:1:20
1 | ls **/*.txt | where { $it.size > 10kb }
  |                     ^^^^^^^^^^^^^^^^^^^ Expected shorthand path, found array literal or index operator
```

I'm not sure if I'm doing something wrong, or if Nu has evolved and what I read was outdated, but I thought I'd mention it.

**Comment by jonathandturner** [comment]
This should be fixed now. Apologies for the *very* long delay in replying
