### ISSUE TITLE
Add dependencies installation instructions for RHEL based OSs

### ISSUE THREAD

**Issue by arnaldo2792** [nushell/book#44]
The dependencies names change from DEB to RHEL, there should be a section for that in the book:

|Deb|RHEL|
|-----|------|
|libxcb-composite0-dev|libxcb|
|openssl|libssl-dev|
|libx11-dev|libX11-devel|

**Comment by jonathandturner** [comment]
@arnaldo2792 - we should definitely add this. Are you interested in writing a PR?

**Comment by jonathandturner** [comment]
This is fixed now. Apologies for the very long delay
