### ISSUE TITLE
Table misalignment

### ISSUE THREAD

**Issue by jonathandturner** [nushell/book#59]
Not sure if the book is using the latest fixes we did for tables, but I noticed that the tables aren't rendering properly in Firefox on Windows:

![image](https://user-images.githubusercontent.com/547158/72851465-94984680-3d10-11ea-90d4-2eb9a4fdb065.png)

From: https://www.nushell.sh/book/en/configuration.html

**Comment by sebastian-xyz** [comment]
I updated all the books to include the latest fix
