### ISSUE TITLE
Add new chapter to book

### ISSUE THREAD

**Issue by jonathandturner** [nushell/book#62]
I recently add https://github.com/nushell/book/blob/master/en/coming_from_bash.md, but I'm not quite sure how to add it to the book.  I've added it to the SUMMARY.md, but looks like that might not be enough to include it.

**Comment by sebastian-xyz** [comment]
Oh yes sorry. Should have given a description on how to add a new chapter.

But you figured it out correctly . :)
The only thing that's missing now is the entry in the sidebar.

Here are hopefully all the steps that are necessary for adding  new chapter at the moment:

1. Add this to the top of the new file and adapt it to your needs. `next` and `prev` are the texts on the buttons on the bottom.
```
---
layout: content
title: TITLE OF THE NEW CHAPTER
prev: NAME OF PREVIOUS BOOK PAGE
next: NAME OF THE NEXT BOOK PAGE
link_prev: /LANGUAGE/PREVIOUS_FILE_NAME.html
link_next: /LANGUAGE/NEXT_FILE_NAME.html
---
```

For example:

```
---
layout: content
title: Introduction
prev: Installation
next: Moving Around
link_prev: /en/installation.html
link_next: /en/moving_around.html
---
```

2. Add the new chapter to the language specific table of contents  
For example for a new english chapter add it to `en/table_of_contents.md`

3. Add it to list of available chapters in the sidebar list:
Enter the correct line for your new chapter in `_includes/navigation.html`

```html
...
<div id="Sidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a id="lang_en" href="#" class="hide" data-toggle="#list_en" onclick="changeColor(this.id)">English</a>
  <ol id="list_en">
    <li><a href="{{ '/en/installation.html' | relative_url }}">Installation</a></li>
    <li><a href="{{ '/en/introduction.html' | relative_url }}">Introduction</a></li>
    <li><a href="{{ '/en/moving_around.html' | relative_url }}">Moving around</a></li>
    <li><a href="{{ '/en/types_of_data.html' | relative_url }}">Types of data</a></li>
    <li><a href="{{ '/en/loading_data.html' | relative_url }}">Loading data</a></li>
    <li><a href="{{ '/en/working_with_tables.html' | relative_url }}">Tables</a></li>
    <li><a href="{{ '/en/pipeline.html' | relative_url }}">Pipeline</a></li>
    <li><a href="{{ '/en/configuration.html' | relative_url }}">Configuration</a></li>
    <li><a href="{{ '/en/metadata.html' | relative_url }}">Metadata</a></li>
    <li><a href="{{ '/en/shells_in_shells.html' | relative_url }}">Shells</a></li>
    <li><a href="{{ '/en/escaping.html' | relative_url }}">Escaping</a></li>
    <li><a href="{{ '/en/plugins.html' | relative_url }}">Plugins</a></li>
  </ol>
...
```

For example for `Coming from Bash` add the following line below `Plugins`:
```html
<li><a href="{{ '/en/coming_from_bash.html' | relative_url }}">From Bash</a></li>
```

Maybe we should make the adding more automatic.

**Comment by jonathandturner** [comment]
This is fixed now, closing
