### ISSUE TITLE
Some inaccuracies in 'Coming from bash'

### ISSUE THREAD

**Issue by kvrhdn** [nushell/book#64]
Hi, I noticed some inaccuracies in the new 'Coming from bash' page.

I though I would list them here first so we can discuss. But I can make quick PR as well.

1. *Save string into a file*: the bash equivalent of `... | save --raw <path>` would be `... > <path>`
1. There are several examples of nu commands with a short flag (like `cp -r <source> <dest>`), but these don't work yet on my version of nu (I have to do `cp <source> <dest> --recursive`). Is this an upcoming feature?

**Comment by jonathandturner** [comment]
1. That's a good catch. I'll update it.
2. Yes, I'll mention that this assumes 0.9.1 or later

**Comment by koenaad** [comment]
Great, thanks 🙂

**Comment by jonathandturner** [comment]
Fixed long ago but forgot to close
